### ISSUE TITLE
A typo in filename which causes error when loading mod (win10 tmod0.11)

### ISSUE THREAD

**Issue by konosubakonoakua** [PhoenixBladez/SpiritMod#31]
it should be pascal style.
![image](https://user-images.githubusercontent.com/42881610/120097767-ed79b980-c164-11eb-8d6a-d720b903a42f.png)

should we just delete the wrong one?
![image](https://user-images.githubusercontent.com/42881610/120097741-cfac5480-c164-11eb-867f-64043ff610dc.png)

**Comment by Trivaxy** [comment]
Fixed.

**Comment by Steviegt6** [comment]
Git handles this stuff very poorly.
